# You can find the documentation at 
# https://docs.fastlane.tools#
# https://docs.fastlane.tools/actions
# https://docs.fastlane.tools/plugins/available-plugins

current_scheme_build_name = "Runner"
signature_method = "enterprise"
path_to_json = "GoogleService-Info.plist"
path_to_build = "../build/ios/iphoneos/"
output_ipa_name = "ideal_atm.ipa"

firebase_cli_token = ENV["firebase_cli_token"]
firebase_app_id = ENV["firebase_app_id_ios"]
bundle_id = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
qa_team_id = ENV["developer_team_id"]
tester_group = ENV["tester_group"]

default_platform(:ios)

platform :ios do
  desc "Deploy a new version to the App Distribution"
  lane :upload_to_app_distribution do
    codesign_app

    firebase_app_distribution(
      app: firebase_app_id,
      googleservice_info_plist_path: path_to_json,
      firebase_cli_token: firebase_cli_token,
      release_notes: "Some change log about current build",
      groups: tester_group
    )
  end

  private_lane :codesign_app do
    sigh(
      app_identifier: bundle_id,
      readonly: true,
      team_id: qa_team_id
    )

    gym(
      scheme: current_scheme_build_name,
      output_name: output_ipa_name,
      silent: true,
      export_method: signature_method,
      build_path: path_to_build,
      export_team_id: qa_team_id
    )
  end
end
